service: sls-plugins-2

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1

iamRoleStatements:
  - Effect: "Allow"
    Action:
      - "dynamodb:*"
    Resource:
      Fn::Join:
        - ""
        - - "arn:aws:s3:::"
          - "Ref" : "UsersDynamoDB"

functions:
  get:
    handler: handler.getUsers
    events:
      - http:
         path: users
         method: get
  post:
    handler: handler.createUser
    events:
      - http:
         path: users
         method: post

# you can add CloudFormation resource templates here
resources:
  Resources:
    UsersDynamoDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "Name"
            AttributeType: "S"
          -
            AttributeName: "EmailAddress"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "Name"
            KeyType: "HASH"
          -
            AttributeName: "EmailAddress"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: "users"
