service: sls-plugins-2

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  stage: dev

functions:
  get:
    handler: handler.getUsers
    events:
      - http:
         path: users
         method: get
  post:
    handler: handler.createUser
    events:
      - http:
         path: users
         method: post

custom:
  stage: ${opt:stage, self:provider.stage}

plugins:
  - plugin

# you can add CloudFormation resource templates here
resources:
  Resources:
    UsersDynamoDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "Name"
            AttributeType: "S"
          -
            AttributeName: "EmailAddress"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "Name"
            KeyType: "HASH"
          -
            AttributeName: "EmailAddress"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
        TableName: "users-${self:custom.stage}"
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: UsersDynamoDB
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Scan
                - dynamodb:UpdateItem
              Resource: "arn:aws:dynamodb:*:*:table/users-${self:custom.stage}"
        Roles:
          - Ref: IamRoleLambdaExecution
